name: "Require all reviewers' approvals"
description: 'Succeed if all the reviewers in the PR has approved, or fail'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/reviewstatus.sh
      shell: bash
