on: [pull_request, pull_request_review]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Run
      uses: yuichielectric/require-all-reviewers-approvals@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
